### ISSUE TITLE
Wallet - display in Main page

### ISSUE THREAD

**Issue by pan1907** [Musicoin/PM#69]
Show “My wallet” in section C in Main page. If click, show current balance, “History”, “Go Mine”, “Send Coins”

**Comment by phiferd** [comment]
The web3 API does not have an efficient method for search for transactions from/to a particular wallet account.  Unfortunately, this means that the page will be *very* slow to load history (as I must scan every transaction and check the to/from addresses) or I will need to basically index the history.  This would me a slow scan once going back to some max block, and then incremental updates. 

This can be done, but I'm not sure it's worth the effort on the client.

**Comment by immartian** [comment]
if so, can we put this history into backlog, leaving to next MVPs and merging together with blockhcain scan prototoype, @cwlau ?

**Comment by cwlau** [comment]
Yes, it is similar to a tx history of an address to be shown in blockchain scan page.

**Comment by immartian** [comment]
so maybe we have a stub for this page(say blocks.musicoin.org) and api, a simplest one is ok for Dan's demo.

**Comment by cwlau** [comment]
Just added http://blocks.musicoin.org/api/history/?address=0x21eew as a stub page.  Required param `address` through it can be anything right now.

**Comment by phiferd** [comment]
Ideally this API will return information that is at a higher level.  e.g. Each item should indicate it if was a PPP, tip, or transfer, rather than just the tx details.  Otherwise, the UI won't be very useful.  Given that this is just a mock, can we change it to include this high-level information?  low-level details can still be included.
